### ISSUE TITLE
Пользователь. Опциональные поля (is_friend, can_write_private_message)

### ISSUE THREAD

**Issue by nafanz** [sgaynetdinov/py-vkontakte#29]
Подскажите, пожалуйста, как можно получить опциональные поля пользователя?

- [x] `is_friend`
- [x] `can_write_private_message`

https://vk.com/dev/objects/user

**Comment by sgaynetdinov** [comment]
Данный полей у `User` нету. Вы можете создать PR и добавить их сюда https://github.com/sgaynetdinov/py-vkontakte/blob/master/vk/users.py#L30

**Comment by nafanz** [comment]
Добавил только `can_write_private_message`
https://github.com/sgaynetdinov/py-vkontakte/pull/30

```
user.is_friend = bool(json_obj.get('is_friend'))
```

`is_friend` у меня почему-то всегда `False` возвращает.

```
import vk
api = vk.Api('xxx')

user = api.get_user('svetlolika_22')
user.can_write_private_message
True
user.is_friend
False

user = api.get_user('durov')
user.can_write_private_message
False
user.is_friend
False
```

**Comment by sgaynetdinov** [comment]
> user.is_friend = bool(json_obj.get('is_friend'))

токен пользователя или сообщества, может в этом дело?

**Comment by sgaynetdinov** [comment]
для этих полей нужно добавить тесты, они простые по типу `https://github.com/sgaynetdinov/py-vkontakte/blob/master/tests/test_user.py#L78`

тогда и поле `is_friend` можно смело использовать, тк мы проверили что данное поле корректно работает при True/False

**Comment by nafanz** [comment]
> токен пользователя или сообщества, может в этом дело?

Вроде как пользователя. Это можно как-то проверить?
Извини, я плохо разбираюсь в этом.

* Создал Standalone-приложение
* Открыл в браузере `https://oauth.vk.com/authorize?client_id=ХХХ&response_type=token`
* Использую этот токен

>для этих полей нужно добавить тесты, они простые по типу

Попробую разобраться в этом

**Comment by sgaynetdinov** [comment]
> > токен пользователя или сообщества, может в этом дело?
> 
> Вроде как пользователя. Это можно как-то проверить?
> Извини, я плохо разбираюсь в этом.
> 
> * Создал Standalone-приложение
> * Открыл в браузере `https://oauth.vk.com/authorize?client_id=ХХХ&response_type=token`
> * Использую этот токен
> 
> > для этих полей нужно добавить тесты, они простые по типу
> 
> Попробую разобраться в этом

что показывает это поле на этой странице https://vk.com/dev/users.get ?
поле дополнительно нужно указать в `fields`

**Comment by nafanz** [comment]
На этой странице значение корректное `"is_friend": 1`
Я первым делом с ней сверялся.

```
{
"response": [{
"id": 9372744,
"first_name": "Анна",
"last_name": "Блуметич",
"is_closed": false,
"can_access_closed": true,
"is_friend": 1
}]
}
```

Почему тут другой ответ я не понимаю.

```
user = api.get_user(9372744)
user.is_friend
False
```

**Comment by sgaynetdinov** [comment]
какая версия api указана на странице https://vk.com/dev/users.get ?
может в этом дело  🤔

**Comment by nafanz** [comment]
5.103
![Снимок экрана от 2020-05-12 22-31-05](https://user-images.githubusercontent.com/36957143/81726187-6a75ba80-94a0-11ea-8f7a-43bf39efce9c.png)

**Comment by sgaynetdinov** [comment]
@nafanz добавил поле 'User.is_friend', проверь пожалуйста оно у тебя корректно работает?

**Comment by nafanz** [comment]
@sgaynetdinov да, спасибо.
Скорее всего в тот раз я забыл в `USER_FIELDS` добавить `is_friend`.
Извини, за беспокойство.
