### ISSUE TITLE
 'module' object has no attribute 'get_friends'

### ISSUE THREAD

**Issue by DenisScy** [sgaynetdinov/py-vkontakte#3]
Try to get friend list via:
vk.get_friends('341988443') 
Result: Traceback (most recent call last): 
File "<pyshell#16>", line 1, in <module> 
vk.get_friends('341988443') 
AttributeError: 'module' object has no attribute 'get_friends'
It is my mistake or trouble?

**Comment by sgaynetdinov** [comment]
Try it
```
>>> user = vk.get_user('durov')
>>> user.get_friends()
```

**Comment by sgaynetdinov** [comment]
@DenisScy it's working?
